### ISSUE TITLE
acmeinit.late.sh and acmeinit.early.sh are missing executable bit

### ISSUE THREAD

**Issue by yorickdowne** [flobernd/docker-haproxy-acme#3]
`/usr/local/bin/acmeinit.late.sh` is missing the `x` permission, ditto `/usr/local/bin/acmeinit.early.sh`. This leads to
```
haproxy-1  | /bin/bash: line 1: /usr/local/bin/acmeinit.late.sh: Permission denied
haproxy-1  | /bin/bash: line 1: exec: /usr/local/bin/acmeinit.late.sh: cannot execute: Permission denied
haproxy-1  | 2024-06-11 21:45:25,612 WARN exited: acmeinit (exit status 126; not expected)
```

Tested with `ghcr.io/flobernd/haproxy-acme-dns01:latest`

**Comment by flobernd** [comment]
Hi @yorickdowne, thanks for reporting! I released a fixed 2.9 version and as well a new image based on haproxy 3.0.

**Comment by yorickdowne** [comment]
I appreciate you and the work you put into this. I wasn’t looking forward to “dockerizing” haproxy with acme.

On that version 3.0: Sounds interesting, but all I see are a 2 and 2.9 tag on ghcr.io

**Comment by flobernd** [comment]
Seems like my deployment workflow ran into rate limits 😵‍💫 https://github.com/flobernd/docker-haproxy-acme/actions/runs/9478593825

I started the workflow again. Let's hope for the best now. Otherwise I'll probably have to wait until tomorrow for the rate limit to hopefully be lifted again.
