### ISSUE TITLE
CI may have created a flawed image

### ISSUE THREAD

**Issue by yorickdowne** [flobernd/docker-haproxy-acme#5]
The file `/usr/local/share/acme/deploy/haproxy.sh` contains `404: Not Found`, causing haproxy to not start.

Tested with `ghcr.io/flobernd/haproxy-acme-dns01:latest`

**Comment by yorickdowne** [comment]
Tried `2.9` as well, same issue

**Comment by flobernd** [comment]
Seems like the deploy script got merged to the upstream `acme.sh` repository. It was previously only available from the `haproxy` repo and downloaded in the Dockerfile (and I forgot to pass `--fail` to `curl` which allowed the build process to continue even tho a `404` was returned).

Removing the download step should fix this problem. I'll take a look.

**Comment by flobernd** [comment]
Should be fixed for `3.0` now. `2.9` is currently being deployed as well.

**Comment by yorickdowne** [comment]
Confirmed that it works now. Thanks for being so quick to fix this!
